# Université Paul Sabatier
# M1 IAFA - Foundations of Information Retrieval - 2026

Instructors: Lynda Tamine, Karim Radouane and Ahmed Rayane Kebir

Notebook proposed by : Jesús Lovón and José G. Moreno

---

💡 Consider developing auxiliary scripts and functions that will enable you to reuse recurring commands in this practical work (PW) and future ones. This would help you keeping good code practice and make debugging easier.


### Attention❗ About TP grading:
🚨 *Code questions*: Fill in the missing code in the corresponding sections (commented code gets the best marks).

🚨 *Open questions*: Write your textual answer as a comment in the corresponding cells.

🚨 *Keep your outputs*: **Empty outputs (notebook or non-executed cells) correspond to 0 points**.

---

# TP 4. PyTerrier - Neural Re-Ranking

In this PW you will learn to:

 - reclassify documents using neural models such as KNRM, Vanilla BERT, EPIC and monoT5.

## Installations and Setup

> 👉 This PW requires *GPU runtime*

- Installing PyTerrier and  PyTerrier plug-ins  

> We install the PyTerrier plugins [OpenNIR](https://opennir.net/) and [monoT5](https://github.com/terrierteam/pyterrier_t5). You can safely ignore package version errors.

In [2]:
!pip install -q --upgrade python-terrier
!pip install -q --upgrade git+https://github.com/Georgetown-IR-Lab/OpenNIR
!pip install -q --upgrade git+https://github.com/terrierteam/pyterrier_t5

  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.8/208.8 kB 5.5 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.1/866.1 kB 21.5 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 46.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 56.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 303.7/303.7 kB 23.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 100.1 MB/s eta 0:00:0000:01
  Building wheel for warc3-wet-clueweb09 (setup.py) ... done
  Building wheel for cbor (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.7/74.7 kB 196.9 kB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.3/114.3 kB 60.2 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.1/158.1 kB 23.4 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 143.4 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 4.7 MB/s eta 0:00:00a 0:00:01
  Building wheel for OpenNIR (setup.py) ... done
  Building wheel for sqlitedict (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
preprocessing 0.1.13 requires nltk==3.2.4, but you have nltk 3.9.4 which is incompatible.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for pyterrier-t5 (pyproject.toml) ... done

We initialize PyTerrier and import libraries as usual

In [5]:
import os
import pyterrier as pt
from pyterrier.measures import * # allow for natural measure names
import onir_pt


# Init PyTerrier
if not pt.started():
    pt.init()

cord19 = pt.datasets.get_dataset('irds:cord19/trec-covid')

<ipython-input-5-9370e26d0058>:8: DeprecationWarning: Call to deprecated function (or staticmethod) started. (use pt.java.started() instead) -- Deprecated since version 0.11.0.
  if not pt.started():

You are already familiarized with the indexation for CORD19

In [6]:
import os
!rm -rf ./terrier_cord19/

pt_index_path = './terrier_cord19'

if not os.path.exists(pt_index_path + "/data.properties"):
    # create the index, using the IterDictIndexer indexer
    indexer = pt.index.IterDictIndexer(pt_index_path, text_attrs=['abstract'], meta=['title','docno'])

    # we give the dataset get_corpus_iter() directly to the indexer
    # while specifying the fields to index and the metadata to record
    # index_ref = indexer.index(cord19.get_corpus_iter(),
    #                           text_attrs=['abstract'])
    indexref = indexer.index(cord19.get_corpus_iter(), )

else:
    # if you already have the index, use it.
    indexref = pt.IndexRef.of(pt_index_path + "/data.properties")

index = pt.IndexFactory.of(indexref)

[INFO] [starting] building docstore
[INFO] If you have a local copy of https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/80d664e496b8b7e50a39c6f6bb92e0ef
[INFO] [starting] https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv
docs_iter:   0%|                                    | 0/192509 [513ms<?, ?doc/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 0.0%| 0.00/269M [0ms<?, ?B/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 0.0%| 24.6k/269M [120ms<21:52, 205kB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 0.0%| 73.7k/269M [247ms<15:02, 298kB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 0.1%| 180k/269M [375ms<09:19, 481kB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 0.1%| 385k/269M [502ms<05:50, 767kB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 0.3%| 786k/269M [630ms<03:35, 1.25MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 0.6%| 1.61M/269M [757ms<02:06, 2.12MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 0.9%| 2.42M/269M [889ms<01:38, 2.73MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 2.0%| 5.25M/269M [1.01s<50.94s, 5.18MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 3.0%| 8.08M/269M [1.15s<37.20s, 7.02MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 4.1%| 10.9M/269M [1.40s<33.19s, 7.78MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 5.1%| 13.7M/269M [1.65s<30.74s, 8.31MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 6.1%| 16.6M/269M [1.79s<27.27s, 9.26MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 7.2%| 19.4M/269M [2.04s<26.27s, 9.51MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 8.2%| 22.2M/269M [2.17s<24.17s, 10.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 9.3%| 25.0M/269M [2.42s<23.64s, 10.3MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 10.3%| 27.9M/269M [2.56s<22.17s, 10.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 11.4%| 30.7M/269M [2.81s<21.81s, 10.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 12.4%| 33.5M/269M [2.94s<20.70s, 11.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 13.5%| 36.3M/269M [3.19s<20.42s, 11.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 14.5%| 39.2M/269M [3.32s<19.53s, 11.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 15.6%| 42.0M/269M [3.56s<19.29s, 11.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 16.6%| 44.8M/269M [3.70s<18.55s, 12.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 17.7%| 47.6M/269M [3.84s<17.86s, 12.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 18.7%| 50.5M/269M [4.08s<17.68s, 12.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 19.8%| 53.3M/269M [4.22s<17.09s, 12.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 20.8%| 56.1M/269M [4.35s<16.52s, 12.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 21.9%| 58.9M/269M [4.59s<16.37s, 12.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 22.9%| 61.8M/269M [4.73s<15.88s, 13.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 24.0%| 64.6M/269M [4.86s<15.40s, 13.3MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 25.0%| 67.4M/269M [5.10s<15.26s, 13.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 26.1%| 70.3M/269M [5.24s<14.83s, 13.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 27.1%| 73.1M/269M [5.37s<14.42s, 13.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 28.2%| 75.9M/269M [5.61s<14.28s, 13.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 29.2%| 78.7M/269M [5.74s<13.90s, 13.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 30.3%| 81.6M/269M [5.88s<13.53s, 13.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 31.3%| 84.4M/269M [6.11s<13.39s, 13.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 32.4%| 87.2M/269M [6.25s<13.05s, 13.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 33.4%| 90.0M/269M [6.39s<12.71s, 14.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 34.5%| 92.9M/269M [6.52s<12.39s, 14.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 35.5%| 95.7M/269M [6.76s<12.25s, 14.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 36.6%| 98.5M/269M [6.89s<11.94s, 14.3MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 37.6%| 101M/269M [7.03s<11.64s, 14.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 38.7%| 104M/269M [7.16s<11.35s, 14.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 39.7%| 107M/269M [7.40s<11.21s, 14.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 40.8%| 110M/269M [7.53s<10.93s, 14.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 41.8%| 113M/269M [7.67s<10.65s, 14.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 42.9%| 115M/269M [7.80s<10.39s, 14.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 43.9%| 118M/269M [8.03s<10.25s, 14.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 45.0%| 121M/269M [8.17s<9.99s, 14.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 46.0%| 124M/269M [8.30s<9.73s, 14.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 47.1%| 127M/269M [8.44s<9.48s, 15.0MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 48.1%| 130M/269M [8.70s<9.37s, 14.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 49.2%| 132M/269M [8.81s<9.10s, 15.0MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 50.2%| 135M/269M [9.06s<8.97s, 14.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 51.3%| 138M/269M [9.32s<8.85s, 14.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 52.3%| 141M/269M [9.57s<8.72s, 14.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 53.4%| 144M/269M [9.85s<8.59s, 14.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 54.4%| 147M/269M [10.20s<8.53s, 14.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 55.5%| 149M/269M [10.46s<8.39s, 14.3MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 56.5%| 152M/269M [10.72s<8.24s, 14.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 57.6%| 155M/269M [10.99s<8.10s, 14.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 58.6%| 158M/269M [11.33s<7.99s, 13.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 59.7%| 161M/269M [11.60s<7.83s, 13.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 60.7%| 164M/269M [11.86s<7.67s, 13.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 61.8%| 166M/269M [12.12s<7.49s, 13.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 62.8%| 169M/269M [12.38s<7.32s, 13.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 63.9%| 172M/269M [12.63s<7.14s, 13.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 64.9%| 175M/269M [12.89s<6.96s, 13.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 66.0%| 178M/269M [13.15s<6.78s, 13.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 67.0%| 180M/269M [13.41s<6.59s, 13.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 68.1%| 183M/269M [13.68s<6.41s, 13.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 69.1%| 186M/269M [14.04s<6.27s, 13.3MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 70.2%| 189M/269M [14.41s<6.12s, 13.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 71.2%| 192M/269M [14.78s<5.97s, 13.0MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 72.3%| 195M/269M [15.07s<5.78s, 12.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 73.3%| 197M/269M [15.43s<5.61s, 12.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 74.4%| 200M/269M [15.71s<5.41s, 12.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 75.4%| 203M/269M [16.07s<5.23s, 12.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 76.5%| 206M/269M [16.43s<5.05s, 12.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 77.5%| 209M/269M [16.71s<4.84s, 12.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 78.6%| 212M/269M [16.99s<4.63s, 12.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 79.6%| 214M/269M [17.35s<4.44s, 12.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 80.7%| 217M/269M [17.85s<4.27s, 12.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 81.7%| 220M/269M [18.37s<4.11s, 12.0MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 82.8%| 223M/269M [18.98s<3.95s, 11.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 83.8%| 226M/269M [19.51s<3.76s, 11.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 84.9%| 229M/269M [20.03s<3.57s, 11.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 85.9%| 231M/269M [20.55s<3.36s, 11.3MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 87.0%| 234M/269M [21.07s<3.15s, 11.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 88.0%| 237M/269M [21.58s<2.93s, 11.0MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 89.1%| 240M/269M [22.09s<2.71s, 10.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 90.1%| 243M/269M [22.60s<2.47s, 10.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 91.2%| 245M/269M [23.11s<2.23s, 10.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 92.2%| 248M/269M [23.62s<1.99s, 10.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 93.3%| 251M/269M [24.13s<1.74s, 10.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 94.3%| 254M/269M [24.64s<1.48s, 10.3MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 95.4%| 257M/269M [25.14s<1.22s, 10.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 96.4%| 260M/269M [25.65s<949ms, 10.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 97.5%| 262M/269M [26.16s<676ms, 10.0MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 98.5%| 265M/269M [26.67s<397ms, 9.95MB/s]
                                                                                ta.csv: 99.6%| 268M/269M [27.17s<114ms, 9.87MB/s]
[INFO] [finished] https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: [27.40s] [269MB] [9.83MB/s]
docs_iter:   0%|                                   | 0/192509 [27.93s<?, ?doc/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: [27.41s] [269MB] [9.82MB/s]
docs_iter: 100%|██████████████████████| 192509/192509 [36.51s<0ms, 5272.76doc/s]
[INFO] [finished] docs_iter: [36.51s] [192509doc] [5272.53doc/s]
[INFO] [finished] building docstore [36.52s]
cord19/trec-covid documents:   0%|          | 59/192509 [672ms<33:57, 94.48it/s]

15:26:44.379 [ForkJoinPool-1-worker-3] WARN org.terrier.structures.indexing.Indexer -- Adding an empty document to the index (6iu1dtyl) - further warnings are suppressed

cord19/trec-covid documents: 100%|██████████| 192509/192509 [48.05s<0ms, 4006.48it/s]

15:27:31.822 [ForkJoinPool-1-worker-3] ERROR org.terrier.structures.indexing.Indexer -- Could not finish MetaIndexBuilder:
java.io.IOException: Key 8lqzfj2e is not unique: 37597,11755
F55
For Mns.FSOrderedMapFile$MultiFSOMapWriter.mergeTwo(FSOrderedMapFile.java:1374)
	at org.terrier.structures.collections.FSOrderedMapFile$MultiFSOMapWriter.close(FSOrderedMapFile.java:1308)
	at org.terrier.structures.indexing.BaseMetaIndexBuilder.close(BaseMetaIndexBuilder.java:321)
	at org.terrier.structures.indexing.classical.BasicIndexer.indexDocuments(BasicIndexer.java:270)
	at org.terrier.structures.indexing.classical.BasicIndexer.createDirectIndex(BasicIndexer.java:388)
	at org.terrier.structures.indexing.Indexer.index(Indexer.java:377)
	at org.terrier.python.ParallelIndexer$3.apply(ParallelIndexer.java:131)
	at org.terrier.python.ParallelIndexer$3.apply(ParallelIndexer.java:120)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558)
	at org.terrier.python.ParallelIndexer$4.call(ParallelIndexer.java:140)
	at org.terrier.python.ParallelIndexer$4.call(ParallelIndexer.java:137)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
15:27:37.654 [ForkJoinPool-1-worker-3] WARN org.terrier.structures.indexing.Indexer -- Indexed 54937 empty documents

# I. Re-Rankers

Let's start exploring some neural re-ranking methods! We can build them from scratch using `onir_pt.reranker`.

OpenNIR's re-ranking model is composed of :
 - `ranker` (for example, `drmm`, `knrm`, or `pacrr`). This defines the neural architecture for ranking.
 - `vocab` (for example, `wordvec_hash`, or `bert`). This defines how the text is encoded by the model. This approach makes it easy to exchange different text representations.

Running this line will take a few minutes, as it downloads and prepares the word vectors.

In [7]:
knrm = onir_pt.reranker('knrm', 'wordvec_hash', text_field='abstract')

config file not found: config
[2026-03-26 15:28:07,830][WordvecHashVocab][DEBUG] [starting] downloading https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip

[2026-03-26 15:28:11,989][onir.util.download][WARNING] no hash provided for https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip; consider adding expected_md5="3cc8839ac3fa9a6187149b1e73328b2a" to ensure data integrity.

[2026-03-26 15:28:11,996][onir.util.download][DEBUG] downloaded https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip [4.07s] [682M] [166MB/s]

[2026-03-26 15:28:12,003][WordvecHashVocab][DEBUG] [finished] downloading https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip [4.17s]
[2026-03-26 15:28:12,005][WordvecHashVocab][DEBUG] [starting] extracting vecs
[2026-03-26 15:28:23,111][WordvecHashVocab][DEBUG] [finished] extracting vecs [11.11s]
[2026-03-26 15:28:23,113][WordvecHashVocab][DEBUG] [starting] loading vecs into memory
[2026-03-26 15:30:23,513][WordvecHashVocab][DEBUG] [finished] loading vecs into memory [02:00]
[2026-03-26 15:30:23,922][WordvecHashVocab][DEBUG] [starting] writing cached at /root/data/onir/vocab/wordvec_hash/fasttext-wiki-news-300d-1M.p
[2026-03-26 15:30:27,341][WordvecHashVocab][DEBUG] [finished] writing cached at /root/data/onir/vocab/wordvec_hash/fasttext-wiki-news-300d-1M.p [3.42s]

Let's see how these models work for ranking!

Similar to previous PWs, we load the topics (queries) and qrels.

Then, we create train/dev/test splits for CORD19.

At this stage, we evaluate directly our models (without training).

In [8]:
tfidf = pt.BatchRetrieve(indexref, wmodel="TF_IDF") % 50
get_text = pt.text.get_text(cord19, 'abstract') #>> pt.apply.title_abstract(lambda r: r['title'] + ' ' + r['abstract'])

<ipython-input-8-d22df401b6fc>:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  tfidf = pt.BatchRetrieve(indexref, wmodel="TF_IDF") % 50

In [9]:
topics = cord19.get_topics(variant='description')
qrels = cord19.get_qrels()

[INFO] [starting] https://ir.nist.gov/covidSubmit/data/topics-rnd5.xml
[INFO] [finished] https://ir.nist.gov/covidSubmit/data/topics-rnd5.xml: [1ms] [18.7kB] [37.2MB/s]
[INFO] [starting] https://ir.nist.gov/covidSubmit/data/qrels-covid_d5_j0.5-5.txt
[INFO] [finished] https://ir.nist.gov/covidSubmit/data/qrels-covid_d5_j0.5-5.txt: [531ms] [1.14MB] [2.15MB/s]

In [12]:
SEED=42

from sklearn.model_selection import train_test_split

tr_va_topics, test_topics = train_test_split(topics, test_size=15, random_state=SEED)
train_topics, valid_topics =  train_test_split(tr_va_topics, test_size=5, random_state=SEED)


test_qrels = qrels # seulement les annotations des topics en réponse sont utilisés, donc pas de problème si on utilise tout
train_qrels = qrels
valid_qrels = qrels

print("OK")

OK

In [13]:
# build a sub-pipeline to get the concatenated title and abstract text
pipeline = tfidf >> get_text >> knrm
pt.Experiment(
    [tfidf, pipeline],
    test_topics,
    qrels,
    names=['TFIDF', 'TFIDF >> KNRM'],
    eval_metrics=[AP(rel=2), nDCG, nDCG@10, P(rel=2)@10]
)

[2026-03-26 15:30:59,082][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:30:59,085][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:30:59,092][onir_pt][DEBUG] [finished] batches: [2ms] [0it] [?it/s]

/usr/local/lib/python3.10/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #1: TFIDF >> KNRM ((TerrierRetr(TF_IDF) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x78328bad38b0> >> onir(knrm,wordvec_hash)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-03-26 15:31:00,270][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:00,273][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:31:00,654][onir_pt][DEBUG] [finished] batches: [377ms] [188it] [498.59it/s]

            name      nDCG   nDCG@10  AP(rel=2)  P(rel=2)@10
0          TFIDF  0.123589  0.595818   0.054568     0.546667
1  TFIDF >> KNRM  0.112703  0.423958   0.042547     0.360000

This doesn't work very well because the model is not trained; it uses random weights to combine the similarity matrix scores.

# II. Training the re-ranker

You can train re-ranking models in PyTerrier using the `fit` method.

In [14]:
pipeline.fit(
    train_topics,
    train_qrels,
    valid_topics,
    valid_qrels)

[2026-03-26 15:31:15,343][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:31:15,345][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:15,348][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:31:15,478][onir_pt][DEBUG] [finished] batches: [125ms] [63it] [503.71it/s]
[2026-03-26 15:31:15,598][onir_pt][DEBUG] [finished] validation [256ms]
[2026-03-26 15:31:15,600][onir_pt][INFO] pre-validation: 0.0053
[2026-03-26 15:31:15,606][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:15,609][onir_pt][DEBUG] [starting] training
[2026-03-26 15:31:15,611][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:31:15,944][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:16,306][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:17,051][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:17,808][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:18,147][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:18,877][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:19,589][onir_pt][DEBUG] [finished] train pairs: [3.97s] [1024it] [257.73it/s]

[2026-03-26 15:31:19,597][onir_pt][DEBUG] [finished] training [3.99s]
[2026-03-26 15:31:19,600][onir_pt][INFO] training   it=0 loss=0.2451
[2026-03-26 15:31:19,602][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:31:19,604][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:19,607][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:31:19,738][onir_pt][DEBUG] [finished] batches: [127ms] [63it] [496.76it/s]
[2026-03-26 15:31:19,858][onir_pt][DEBUG] [finished] validation [256ms]
[2026-03-26 15:31:19,862][onir_pt][INFO] validation it=0 map=0.0058 ndcg=0.0151 P_10=0.0700 <--
[2026-03-26 15:31:19,865][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:19,868][onir_pt][DEBUG] [starting] training
[2026-03-26 15:31:19,870][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:31:20,039][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:20,101][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:21,325][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:22,028][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:22,244][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:22,565][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:22,659][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:23,015][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:23,392][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:23,533][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:23,646][onir_pt][DEBUG] [finished] train pairs: [3.77s] [1024it] [271.54it/s]

[2026-03-26 15:31:23,653][onir_pt][DEBUG] [finished] training [3.78s]
[2026-03-26 15:31:23,656][onir_pt][INFO] training   it=1 loss=0.2213
[2026-03-26 15:31:23,657][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:31:23,660][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:23,663][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:31:23,795][onir_pt][DEBUG] [finished] batches: [128ms] [63it] [493.70it/s]
[2026-03-26 15:31:23,911][onir_pt][DEBUG] [finished] validation [254ms]
[2026-03-26 15:31:23,915][onir_pt][INFO] validation it=1 map=0.0059 ndcg=0.0152 P_10=0.0700 <--
[2026-03-26 15:31:23,916][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:23,920][onir_pt][DEBUG] [starting] training
[2026-03-26 15:31:23,922][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:31:24,304][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:24,589][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:24,985][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:25,100][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:25,256][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:25,495][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:25,629][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:26,570][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:27,545][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:27,685][onir_pt][DEBUG] [finished] train pairs: [3.76s] [1024it] [272.46it/s]

[2026-03-26 15:31:27,693][onir_pt][DEBUG] [finished] training [3.77s]
[2026-03-26 15:31:27,696][onir_pt][INFO] training   it=2 loss=0.2307
[2026-03-26 15:31:27,698][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:31:27,700][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:27,704][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:31:27,853][onir_pt][DEBUG] [finished] batches: [145ms] [63it] [433.38it/s]
[2026-03-26 15:31:27,971][onir_pt][DEBUG] [finished] validation [273ms]
[2026-03-26 15:31:27,975][onir_pt][INFO] validation it=2 map=0.0059 ndcg=0.0152 P_10=0.0700 <--
[2026-03-26 15:31:27,977][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:27,979][onir_pt][DEBUG] [starting] training
[2026-03-26 15:31:27,982][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:31:27,999][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:29,269][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:29,573][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:29,882][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:30,134][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:30,314][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:31,159][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:31,628][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:32,024][onir_pt][DEBUG] [finished] train pairs: [4.04s] [1024it] [253.64it/s]

[2026-03-26 15:31:32,032][onir_pt][DEBUG] [finished] training [4.05s]
[2026-03-26 15:31:32,035][onir_pt][INFO] training   it=3 loss=0.2306
[2026-03-26 15:31:32,037][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:31:32,039][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:32,042][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:31:32,176][onir_pt][DEBUG] [finished] batches: [129ms] [63it] [488.93it/s]
[2026-03-26 15:31:32,300][onir_pt][DEBUG] [finished] validation [263ms]
[2026-03-26 15:31:32,302][onir_pt][INFO] validation it=3 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-26 15:31:32,304][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:32,308][onir_pt][DEBUG] [starting] training
[2026-03-26 15:31:32,310][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:31:32,575][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:32,863][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:33,005][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:33,805][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:34,213][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:34,532][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:35,823][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:35,946][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:36,283][onir_pt][DEBUG] [finished] train pairs: [3.97s] [1024it] [258.03it/s]

[2026-03-26 15:31:36,291][onir_pt][DEBUG] [finished] training [3.98s]
[2026-03-26 15:31:36,294][onir_pt][INFO] training   it=4 loss=0.2237
[2026-03-26 15:31:36,295][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:31:36,297][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:36,302][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:31:36,433][onir_pt][DEBUG] [finished] batches: [127ms] [63it] [494.67it/s]
[2026-03-26 15:31:36,553][onir_pt][DEBUG] [finished] validation [257ms]
[2026-03-26 15:31:36,555][onir_pt][INFO] validation it=4 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-26 15:31:36,558][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:36,561][onir_pt][DEBUG] [starting] training
[2026-03-26 15:31:36,563][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:31:36,639][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:36,959][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:37,337][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:37,382][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:37,538][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:38,024][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:38,322][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:39,679][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:40,495][onir_pt][DEBUG] [finished] train pairs: [3.93s] [1024it] [260.73it/s]

[2026-03-26 15:31:40,503][onir_pt][DEBUG] [finished] training [3.94s]
[2026-03-26 15:31:40,506][onir_pt][INFO] training   it=5 loss=0.2217
[2026-03-26 15:31:40,508][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:31:40,510][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:40,513][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:31:40,649][onir_pt][DEBUG] [finished] batches: [131ms] [63it] [479.50it/s]
[2026-03-26 15:31:40,766][onir_pt][DEBUG] [finished] validation [259ms]
[2026-03-26 15:31:40,769][onir_pt][INFO] validation it=5 map=0.0058 ndcg=0.0151 P_10=0.0700
[2026-03-26 15:31:40,771][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:40,775][onir_pt][DEBUG] [starting] training
[2026-03-26 15:31:40,776][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:31:41,151][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:41,479][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:43,105][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:43,667][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:44,086][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:44,467][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:44,696][onir_pt][DEBUG] [finished] train pairs: [3.91s] [1024it] [261.59it/s]

[2026-03-26 15:31:44,704][onir_pt][DEBUG] [finished] training [3.93s]
[2026-03-26 15:31:44,707][onir_pt][INFO] training   it=6 loss=0.2109
[2026-03-26 15:31:44,709][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:31:44,711][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:44,713][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:31:44,848][onir_pt][DEBUG] [finished] batches: [129ms] [63it] [487.14it/s]
[2026-03-26 15:31:44,972][onir_pt][DEBUG] [finished] validation [264ms]
[2026-03-26 15:31:44,977][onir_pt][INFO] validation it=6 map=0.0059 ndcg=0.0152 P_10=0.0700 <--
[2026-03-26 15:31:44,978][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:44,981][onir_pt][DEBUG] [starting] training
[2026-03-26 15:31:44,983][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:31:45,455][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:45,619][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:45,896][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:46,013][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:46,139][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:47,168][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:47,515][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:48,430][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:48,664][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:48,785][onir_pt][DEBUG] [finished] train pairs: [3.80s] [1024it] [269.69it/s]

[2026-03-26 15:31:48,793][onir_pt][DEBUG] [finished] training [3.81s]
[2026-03-26 15:31:48,795][onir_pt][INFO] training   it=7 loss=0.2142
[2026-03-26 15:31:48,797][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:31:48,799][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:48,802][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:31:48,932][onir_pt][DEBUG] [finished] batches: [125ms] [63it] [503.00it/s]
[2026-03-26 15:31:49,046][onir_pt][DEBUG] [finished] validation [249ms]
[2026-03-26 15:31:49,049][onir_pt][INFO] validation it=7 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-26 15:31:49,052][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:49,055][onir_pt][DEBUG] [starting] training
[2026-03-26 15:31:49,056][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:31:49,093][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:49,645][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:49,884][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:49,945][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:50,304][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:51,101][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:51,541][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:51,709][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:51,865][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:52,080][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:52,576][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:52,832][onir_pt][DEBUG] [finished] train pairs: [3.77s] [1024it] [271.57it/s]

[2026-03-26 15:31:52,840][onir_pt][DEBUG] [finished] training [3.78s]
[2026-03-26 15:31:52,843][onir_pt][INFO] training   it=8 loss=0.2279
[2026-03-26 15:31:52,845][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:31:52,847][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:52,850][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:31:52,980][onir_pt][DEBUG] [finished] batches: [126ms] [63it] [500.82it/s]
[2026-03-26 15:31:53,092][onir_pt][DEBUG] [finished] validation [247ms]
[2026-03-26 15:31:53,094][onir_pt][INFO] validation it=8 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-26 15:31:53,096][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:53,100][onir_pt][DEBUG] [starting] training
[2026-03-26 15:31:53,101][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:31:53,137][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:53,796][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:54,268][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:54,389][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:54,818][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:55,313][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:55,829][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:56,362][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:56,391][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:56,788][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:56,820][onir_pt][DEBUG] [finished] train pairs: [3.71s] [1024it] [275.69it/s]

[2026-03-26 15:31:56,828][onir_pt][DEBUG] [finished] training [3.73s]
[2026-03-26 15:31:56,830][onir_pt][INFO] training   it=9 loss=0.2264
[2026-03-26 15:31:56,832][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:31:56,835][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:56,838][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:31:56,968][onir_pt][DEBUG] [finished] batches: [126ms] [63it] [500.35it/s]
[2026-03-26 15:31:57,082][onir_pt][DEBUG] [finished] validation [251ms]
[2026-03-26 15:31:57,086][onir_pt][INFO] validation it=9 map=0.0060 ndcg=0.0153 P_10=0.0700 <--
[2026-03-26 15:31:57,088][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:31:57,091][onir_pt][DEBUG] [starting] training
[2026-03-26 15:31:57,093][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:31:57,671][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:57,808][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:58,179][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:58,434][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:58,497][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:59,320][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:59,379][onir_pt][DEBUG] not enough negs

[2026-03-26 15:31:59,960][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:00,403][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:00,828][onir_pt][DEBUG] [finished] train pairs: [3.73s] [1024it] [274.51it/s]

[2026-03-26 15:32:00,835][onir_pt][DEBUG] [finished] training [3.74s]
[2026-03-26 15:32:00,838][onir_pt][INFO] training   it=10 loss=0.2234
[2026-03-26 15:32:00,840][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:00,842][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:00,846][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:00,973][onir_pt][DEBUG] [finished] batches: [123ms] [63it] [510.97it/s]
[2026-03-26 15:32:01,087][onir_pt][DEBUG] [finished] validation [247ms]
[2026-03-26 15:32:01,091][onir_pt][INFO] validation it=10 map=0.0060 ndcg=0.0153 P_10=0.0700 <--
[2026-03-26 15:32:01,093][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:01,095][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:01,098][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:01,634][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:01,712][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:01,991][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:02,434][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:03,052][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:03,743][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:04,241][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:04,810][onir_pt][DEBUG] [finished] train pairs: [3.71s] [1024it] [276.28it/s]

[2026-03-26 15:32:04,817][onir_pt][DEBUG] [finished] training [3.72s]
[2026-03-26 15:32:04,820][onir_pt][INFO] training   it=11 loss=0.2149
[2026-03-26 15:32:04,821][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:04,824][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:04,827][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:04,957][onir_pt][DEBUG] [finished] batches: [126ms] [63it] [500.20it/s]
[2026-03-26 15:32:05,070][onir_pt][DEBUG] [finished] validation [249ms]
[2026-03-26 15:32:05,072][onir_pt][INFO] validation it=11 map=0.0060 ndcg=0.0153 P_10=0.0700
[2026-03-26 15:32:05,074][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:05,077][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:05,079][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:05,324][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:05,489][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:06,876][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:07,263][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:07,370][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:07,610][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:07,981][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:08,442][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:08,760][onir_pt][DEBUG] [finished] train pairs: [3.68s] [1024it] [278.59it/s]

[2026-03-26 15:32:08,767][onir_pt][DEBUG] [finished] training [3.69s]
[2026-03-26 15:32:08,770][onir_pt][INFO] training   it=12 loss=0.2162
[2026-03-26 15:32:08,772][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:08,774][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:08,778][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:08,907][onir_pt][DEBUG] [finished] batches: [125ms] [63it] [504.60it/s]
[2026-03-26 15:32:09,020][onir_pt][DEBUG] [finished] validation [248ms]
[2026-03-26 15:32:09,024][onir_pt][INFO] validation it=12 map=0.0060 ndcg=0.0155 P_10=0.0720 <--
[2026-03-26 15:32:09,026][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:09,029][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:09,031][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:09,269][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:09,329][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:10,023][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:10,220][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:11,547][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:11,817][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:11,909][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:12,252][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:12,725][onir_pt][DEBUG] [finished] train pairs: [3.69s] [1024it] [277.53it/s]

[2026-03-26 15:32:12,733][onir_pt][DEBUG] [finished] training [3.70s]
[2026-03-26 15:32:12,735][onir_pt][INFO] training   it=13 loss=0.2354
[2026-03-26 15:32:12,737][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:12,739][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:12,741][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:12,875][onir_pt][DEBUG] [finished] batches: [129ms] [63it] [486.84it/s]
[2026-03-26 15:32:12,989][onir_pt][DEBUG] [finished] validation [252ms]
[2026-03-26 15:32:12,991][onir_pt][INFO] validation it=13 map=0.0060 ndcg=0.0153 P_10=0.0720
[2026-03-26 15:32:12,993][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:12,997][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:12,999][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:13,242][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:13,699][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:14,407][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:15,351][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:15,536][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:16,702][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:16,741][onir_pt][DEBUG] [finished] train pairs: [3.74s] [1024it] [273.96it/s]

[2026-03-26 15:32:16,748][onir_pt][DEBUG] [finished] training [3.75s]
[2026-03-26 15:32:16,749][onir_pt][INFO] training   it=14 loss=0.2228
[2026-03-26 15:32:16,751][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:16,753][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:16,758][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:16,888][onir_pt][DEBUG] [finished] batches: [126ms] [63it] [498.75it/s]
[2026-03-26 15:32:17,002][onir_pt][DEBUG] [finished] validation [250ms]
[2026-03-26 15:32:17,004][onir_pt][INFO] validation it=14 map=0.0059 ndcg=0.0152 P_10=0.0680
[2026-03-26 15:32:17,006][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:17,009][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:17,011][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:17,025][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:17,239][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:17,836][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:18,044][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:18,234][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:19,208][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:19,986][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:20,093][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:20,271][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:20,534][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:20,732][onir_pt][DEBUG] [finished] train pairs: [3.72s] [1024it] [275.54it/s]

[2026-03-26 15:32:20,739][onir_pt][DEBUG] [finished] training [3.73s]
[2026-03-26 15:32:20,742][onir_pt][INFO] training   it=15 loss=0.2188
[2026-03-26 15:32:20,744][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:20,746][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:20,749][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:20,880][onir_pt][DEBUG] [finished] batches: [126ms] [63it] [499.41it/s]
[2026-03-26 15:32:20,997][onir_pt][DEBUG] [finished] validation [253ms]
[2026-03-26 15:32:20,999][onir_pt][INFO] validation it=15 map=0.0060 ndcg=0.0153 P_10=0.0720
[2026-03-26 15:32:21,001][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:21,006][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:21,008][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:21,283][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:21,610][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:21,674][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:21,764][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:21,916][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:22,157][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:23,978][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:24,039][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:24,737][onir_pt][DEBUG] [finished] train pairs: [3.72s] [1024it] [274.91it/s]

[2026-03-26 15:32:24,745][onir_pt][DEBUG] [finished] training [3.74s]
[2026-03-26 15:32:24,748][onir_pt][INFO] training   it=16 loss=0.2246
[2026-03-26 15:32:24,750][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:24,751][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:24,755][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:24,885][onir_pt][DEBUG] [finished] batches: [126ms] [63it] [500.49it/s]
[2026-03-26 15:32:24,998][onir_pt][DEBUG] [finished] validation [248ms]
[2026-03-26 15:32:25,000][onir_pt][INFO] validation it=16 map=0.0060 ndcg=0.0153 P_10=0.0720
[2026-03-26 15:32:25,003][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:25,006][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:25,007][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:25,126][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:25,698][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:25,872][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:26,271][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:26,365][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:26,811][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:26,919][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:27,595][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:27,776][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:27,848][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:28,206][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:28,718][onir_pt][DEBUG] [finished] train pairs: [3.71s] [1024it] [276.30it/s]

[2026-03-26 15:32:28,726][onir_pt][DEBUG] [finished] training [3.72s]
[2026-03-26 15:32:28,729][onir_pt][INFO] training   it=17 loss=0.2332
[2026-03-26 15:32:28,730][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:28,732][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:28,736][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:28,867][onir_pt][DEBUG] [finished] batches: [126ms] [63it] [498.67it/s]
[2026-03-26 15:32:28,981][onir_pt][DEBUG] [finished] validation [251ms]
[2026-03-26 15:32:28,984][onir_pt][INFO] validation it=17 map=0.0060 ndcg=0.0153 P_10=0.0720
[2026-03-26 15:32:28,986][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:28,989][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:28,991][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:29,013][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:29,082][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:29,377][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:29,536][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:29,895][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:30,541][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:30,811][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:31,268][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:32,369][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:32,725][onir_pt][DEBUG] [finished] train pairs: [3.73s] [1024it] [274.54it/s]

[2026-03-26 15:32:32,732][onir_pt][DEBUG] [finished] training [3.74s]
[2026-03-26 15:32:32,735][onir_pt][INFO] training   it=18 loss=0.2167
[2026-03-26 15:32:32,736][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:32,740][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:32,742][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:32,873][onir_pt][DEBUG] [finished] batches: [127ms] [63it] [497.80it/s]
[2026-03-26 15:32:32,986][onir_pt][DEBUG] [finished] validation [249ms]
[2026-03-26 15:32:32,987][onir_pt][INFO] validation it=18 map=0.0060 ndcg=0.0153 P_10=0.0720
[2026-03-26 15:32:32,989][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:32,993][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:32,994][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:33,426][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:33,602][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:34,622][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:35,471][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:35,623][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:35,771][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:35,936][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:36,716][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:36,757][onir_pt][DEBUG] [finished] train pairs: [3.76s] [1024it] [272.49it/s]

[2026-03-26 15:32:36,765][onir_pt][DEBUG] [finished] training [3.77s]
[2026-03-26 15:32:36,767][onir_pt][INFO] training   it=19 loss=0.2283
[2026-03-26 15:32:36,770][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:36,771][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:36,775][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:36,910][onir_pt][DEBUG] [finished] batches: [130ms] [63it] [483.58it/s]
[2026-03-26 15:32:37,023][onir_pt][DEBUG] [finished] validation [254ms]
[2026-03-26 15:32:37,025][onir_pt][INFO] validation it=19 map=0.0060 ndcg=0.0152 P_10=0.0720
[2026-03-26 15:32:37,027][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:37,032][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:37,033][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:37,315][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:37,373][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:37,484][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:37,643][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:38,844][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:39,296][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:39,641][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:40,283][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:40,974][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:41,122][onir_pt][DEBUG] [finished] train pairs: [4.08s] [1024it] [250.73it/s]

[2026-03-26 15:32:41,130][onir_pt][DEBUG] [finished] training [4.10s]
[2026-03-26 15:32:41,133][onir_pt][INFO] training   it=20 loss=0.2041
[2026-03-26 15:32:41,135][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:41,137][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:41,142][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:41,276][onir_pt][DEBUG] [finished] batches: [130ms] [63it] [485.70it/s]
[2026-03-26 15:32:41,400][onir_pt][DEBUG] [finished] validation [265ms]
[2026-03-26 15:32:41,403][onir_pt][INFO] validation it=20 map=0.0060 ndcg=0.0153 P_10=0.0700
[2026-03-26 15:32:41,405][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:41,410][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:41,412][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:41,592][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:41,995][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:42,119][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:42,418][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:43,367][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:43,643][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:44,172][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:44,453][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:44,650][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:45,471][onir_pt][DEBUG] [finished] train pairs: [4.05s] [1024it] [252.59it/s]

[2026-03-26 15:32:45,479][onir_pt][DEBUG] [finished] training [4.07s]
[2026-03-26 15:32:45,482][onir_pt][INFO] training   it=21 loss=0.2270
[2026-03-26 15:32:45,483][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:45,486][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:45,489][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:45,619][onir_pt][DEBUG] [finished] batches: [125ms] [63it] [503.92it/s]
[2026-03-26 15:32:45,739][onir_pt][DEBUG] [finished] validation [256ms]
[2026-03-26 15:32:45,741][onir_pt][INFO] validation it=21 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-26 15:32:45,743][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:45,747][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:45,749][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:45,901][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:46,302][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:46,495][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:46,858][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:47,583][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:48,173][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:48,460][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:48,705][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:48,713][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:49,554][onir_pt][DEBUG] [finished] train pairs: [3.80s] [1024it] [269.45it/s]

[2026-03-26 15:32:49,563][onir_pt][DEBUG] [finished] training [3.82s]
[2026-03-26 15:32:49,566][onir_pt][INFO] training   it=22 loss=0.2241
[2026-03-26 15:32:49,568][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:49,570][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:49,574][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:49,715][onir_pt][DEBUG] [finished] batches: [137ms] [63it] [461.25it/s]
[2026-03-26 15:32:49,831][onir_pt][DEBUG] [finished] validation [263ms]
[2026-03-26 15:32:49,833][onir_pt][INFO] validation it=22 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-26 15:32:49,835][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:49,839][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:49,841][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:50,205][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:50,436][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:50,652][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:51,148][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:51,468][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:53,048][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:53,459][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:53,672][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:53,685][onir_pt][DEBUG] [finished] train pairs: [3.84s] [1024it] [266.74it/s]

[2026-03-26 15:32:53,694][onir_pt][DEBUG] [finished] training [3.86s]
[2026-03-26 15:32:53,697][onir_pt][INFO] training   it=23 loss=0.2215
[2026-03-26 15:32:53,699][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:53,701][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:53,704][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:53,855][onir_pt][DEBUG] [finished] batches: [144ms] [63it] [436.50it/s]
[2026-03-26 15:32:53,974][onir_pt][DEBUG] [finished] validation [275ms]
[2026-03-26 15:32:53,976][onir_pt][INFO] validation it=23 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-26 15:32:53,978][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:53,981][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:53,984][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:54,430][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:54,506][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:55,012][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:55,789][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:56,822][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:57,236][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:58,165][onir_pt][DEBUG] [finished] train pairs: [4.18s] [1024it] [245.10it/s]

[2026-03-26 15:32:58,173][onir_pt][DEBUG] [finished] training [4.19s]
[2026-03-26 15:32:58,176][onir_pt][INFO] training   it=24 loss=0.2264
[2026-03-26 15:32:58,177][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:32:58,180][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:58,183][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:32:58,315][onir_pt][DEBUG] [finished] batches: [127ms] [63it] [494.14it/s]
[2026-03-26 15:32:58,440][onir_pt][DEBUG] [finished] validation [262ms]
[2026-03-26 15:32:58,441][onir_pt][INFO] validation it=24 map=0.0060 ndcg=0.0153 P_10=0.0700
[2026-03-26 15:32:58,444][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:32:58,447][onir_pt][DEBUG] [starting] training
[2026-03-26 15:32:58,448][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:32:58,648][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:58,999][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:59,549][onir_pt][DEBUG] not enough negs

[2026-03-26 15:32:59,992][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:00,613][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:00,902][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:01,228][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:01,499][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:02,317][onir_pt][DEBUG] [finished] train pairs: [3.86s] [1024it] [265.04it/s]

[2026-03-26 15:33:02,324][onir_pt][DEBUG] [finished] training [3.88s]
[2026-03-26 15:33:02,327][onir_pt][INFO] training   it=25 loss=0.2156
[2026-03-26 15:33:02,329][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:02,333][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:02,336][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:02,487][onir_pt][DEBUG] [finished] batches: [147ms] [63it] [429.24it/s]
[2026-03-26 15:33:02,600][onir_pt][DEBUG] [finished] validation [271ms]
[2026-03-26 15:33:02,602][onir_pt][INFO] validation it=25 map=0.0060 ndcg=0.0153 P_10=0.0700
[2026-03-26 15:33:02,605][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:02,609][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:02,611][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:02,964][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:03,723][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:04,182][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:04,626][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:05,576][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:06,018][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:06,398][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:06,479][onir_pt][DEBUG] [finished] train pairs: [3.86s] [1024it] [265.08it/s]

[2026-03-26 15:33:06,487][onir_pt][DEBUG] [finished] training [3.88s]
[2026-03-26 15:33:06,490][onir_pt][INFO] training   it=26 loss=0.2218
[2026-03-26 15:33:06,491][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:06,494][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:06,498][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:06,634][onir_pt][DEBUG] [finished] batches: [132ms] [63it] [475.50it/s]
[2026-03-26 15:33:06,747][onir_pt][DEBUG] [finished] validation [256ms]
[2026-03-26 15:33:06,749][onir_pt][INFO] validation it=26 map=0.0060 ndcg=0.0153 P_10=0.0720
[2026-03-26 15:33:06,751][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:06,755][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:06,757][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:06,869][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:07,221][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:08,154][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:09,014][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:09,582][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:09,915][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:10,615][onir_pt][DEBUG] [finished] train pairs: [3.85s] [1024it] [265.79it/s]

[2026-03-26 15:33:10,623][onir_pt][DEBUG] [finished] training [3.87s]
[2026-03-26 15:33:10,626][onir_pt][INFO] training   it=27 loss=0.2191
[2026-03-26 15:33:10,628][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:10,630][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:10,634][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:10,766][onir_pt][DEBUG] [finished] batches: [128ms] [63it] [491.32it/s]
[2026-03-26 15:33:10,890][onir_pt][DEBUG] [finished] validation [261ms]
[2026-03-26 15:33:10,892][onir_pt][INFO] validation it=27 map=0.0060 ndcg=0.0153 P_10=0.0720
[2026-03-26 15:33:10,894][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:10,898][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:10,900][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:11,478][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:11,579][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:11,719][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:11,946][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:12,302][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:12,834][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:13,322][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:13,427][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:13,719][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:13,994][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:14,087][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:14,716][onir_pt][DEBUG] [finished] train pairs: [3.81s] [1024it] [268.67it/s]

[2026-03-26 15:33:14,723][onir_pt][DEBUG] [finished] training [3.82s]
[2026-03-26 15:33:14,726][onir_pt][INFO] training   it=28 loss=0.2143
[2026-03-26 15:33:14,728][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:14,729][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:14,733][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:14,863][onir_pt][DEBUG] [finished] batches: [126ms] [63it] [501.27it/s]
[2026-03-26 15:33:14,981][onir_pt][DEBUG] [finished] validation [254ms]
[2026-03-26 15:33:14,984][onir_pt][INFO] validation it=28 map=0.0060 ndcg=0.0153 P_10=0.0720
[2026-03-26 15:33:14,987][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:14,990][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:14,992][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:15,127][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:15,292][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:15,438][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:15,607][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:15,795][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:16,011][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:16,078][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:17,260][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:17,405][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:17,604][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:17,930][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:18,337][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:18,856][onir_pt][DEBUG] [finished] train pairs: [3.86s] [1024it] [265.31it/s]

[2026-03-26 15:33:18,863][onir_pt][DEBUG] [finished] training [3.87s]
[2026-03-26 15:33:18,866][onir_pt][INFO] training   it=29 loss=0.2294
[2026-03-26 15:33:18,868][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:18,870][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:18,874][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:19,008][onir_pt][DEBUG] [finished] batches: [130ms] [63it] [485.69it/s]
[2026-03-26 15:33:19,125][onir_pt][DEBUG] [finished] validation [257ms]
[2026-03-26 15:33:19,128][onir_pt][INFO] validation it=29 map=0.0060 ndcg=0.0153 P_10=0.0700
[2026-03-26 15:33:19,130][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:19,134][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:19,136][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:19,623][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:19,729][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:20,033][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:20,082][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:20,360][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:20,830][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:21,525][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:21,687][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:21,844][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:22,377][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:22,514][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:22,951][onir_pt][DEBUG] [finished] train pairs: [3.81s] [1024it] [268.76it/s]

[2026-03-26 15:33:22,958][onir_pt][DEBUG] [finished] training [3.82s]
[2026-03-26 15:33:22,961][onir_pt][INFO] training   it=30 loss=0.2226
[2026-03-26 15:33:22,962][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:22,964][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:22,968][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:23,100][onir_pt][DEBUG] [finished] batches: [127ms] [63it] [494.70it/s]
[2026-03-26 15:33:23,217][onir_pt][DEBUG] [finished] validation [254ms]
[2026-03-26 15:33:23,219][onir_pt][INFO] validation it=30 map=0.0060 ndcg=0.0153 P_10=0.0700
[2026-03-26 15:33:23,222][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:23,224][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:23,226][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:23,874][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:24,318][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:24,409][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:24,545][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:25,513][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:25,756][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:26,294][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:26,737][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:26,908][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:27,023][onir_pt][DEBUG] [finished] train pairs: [3.79s] [1024it] [270.05it/s]

[2026-03-26 15:33:27,031][onir_pt][DEBUG] [finished] training [3.81s]
[2026-03-26 15:33:27,034][onir_pt][INFO] training   it=31 loss=0.2252
[2026-03-26 15:33:27,035][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:27,037][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:27,042][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:27,174][onir_pt][DEBUG] [finished] batches: [127ms] [63it] [494.92it/s]
[2026-03-26 15:33:27,289][onir_pt][DEBUG] [finished] validation [254ms]
[2026-03-26 15:33:27,291][onir_pt][INFO] validation it=31 map=0.0060 ndcg=0.0153 P_10=0.0740
[2026-03-26 15:33:27,294][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:27,297][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:27,299][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:27,476][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:27,531][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:27,851][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:28,048][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:29,887][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:30,118][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:30,349][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:30,480][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:30,747][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:30,897][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:30,979][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:31,171][onir_pt][DEBUG] [finished] train pairs: [3.87s] [1024it] [264.89it/s]

[2026-03-26 15:33:31,178][onir_pt][DEBUG] [finished] training [3.88s]
[2026-03-26 15:33:31,181][onir_pt][INFO] training   it=32 loss=0.2204
[2026-03-26 15:33:31,184][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:31,187][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:31,190][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:31,323][onir_pt][DEBUG] [finished] batches: [129ms] [63it] [489.98it/s]
[2026-03-26 15:33:31,440][onir_pt][DEBUG] [finished] validation [256ms]
[2026-03-26 15:33:31,443][onir_pt][INFO] validation it=32 map=0.0061 ndcg=0.0154 P_10=0.0720 <--
[2026-03-26 15:33:31,445][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:31,449][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:31,450][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:32,631][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:32,816][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:34,754][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:35,107][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:35,272][onir_pt][DEBUG] [finished] train pairs: [3.82s] [1024it] [268.27it/s]

[2026-03-26 15:33:35,279][onir_pt][DEBUG] [finished] training [3.83s]
[2026-03-26 15:33:35,282][onir_pt][INFO] training   it=33 loss=0.2170
[2026-03-26 15:33:35,284][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:35,286][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:35,288][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:35,420][onir_pt][DEBUG] [finished] batches: [128ms] [63it] [493.32it/s]
[2026-03-26 15:33:35,546][onir_pt][DEBUG] [finished] validation [262ms]
[2026-03-26 15:33:35,548][onir_pt][INFO] validation it=33 map=0.0060 ndcg=0.0153 P_10=0.0720
[2026-03-26 15:33:35,551][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:35,556][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:35,558][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:36,686][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:36,861][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:37,073][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:37,346][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:37,514][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:37,583][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:37,943][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:38,319][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:38,420][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:38,519][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:38,842][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:38,945][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:39,402][onir_pt][DEBUG] [finished] train pairs: [3.84s] [1024it] [266.72it/s]

[2026-03-26 15:33:39,409][onir_pt][DEBUG] [finished] training [3.85s]
[2026-03-26 15:33:39,411][onir_pt][INFO] training   it=34 loss=0.2344
[2026-03-26 15:33:39,414][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:39,416][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:39,419][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:39,551][onir_pt][DEBUG] [finished] batches: [127ms] [63it] [495.86it/s]
[2026-03-26 15:33:39,667][onir_pt][DEBUG] [finished] validation [253ms]
[2026-03-26 15:33:39,669][onir_pt][INFO] validation it=34 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-26 15:33:39,671][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:39,675][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:39,676][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:40,169][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:40,431][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:40,929][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:41,471][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:41,618][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:41,932][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:42,178][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:42,714][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:43,543][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:43,594][onir_pt][DEBUG] [finished] train pairs: [3.91s] [1024it] [261.69it/s]

[2026-03-26 15:33:43,602][onir_pt][DEBUG] [finished] training [3.93s]
[2026-03-26 15:33:43,605][onir_pt][INFO] training   it=35 loss=0.2288
[2026-03-26 15:33:43,606][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:43,609][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:43,613][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:43,751][onir_pt][DEBUG] [finished] batches: [134ms] [63it] [470.80it/s]
[2026-03-26 15:33:43,873][onir_pt][DEBUG] [finished] validation [266ms]
[2026-03-26 15:33:43,875][onir_pt][INFO] validation it=35 map=0.0058 ndcg=0.0150 P_10=0.0740
[2026-03-26 15:33:43,877][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:43,881][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:43,883][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:44,076][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:44,289][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:44,400][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:44,562][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:44,763][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:44,901][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:45,855][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:46,414][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:47,708][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:47,734][onir_pt][DEBUG] [finished] train pairs: [3.85s] [1024it] [266.24it/s]

[2026-03-26 15:33:47,742][onir_pt][DEBUG] [finished] training [3.86s]
[2026-03-26 15:33:47,746][onir_pt][INFO] training   it=36 loss=0.2315
[2026-03-26 15:33:47,747][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:47,749][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:47,752][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:47,881][onir_pt][DEBUG] [finished] batches: [124ms] [63it] [507.74it/s]
[2026-03-26 15:33:48,002][onir_pt][DEBUG] [finished] validation [255ms]
[2026-03-26 15:33:48,004][onir_pt][INFO] validation it=36 map=0.0057 ndcg=0.0149 P_10=0.0660
[2026-03-26 15:33:48,006][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:48,011][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:48,013][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:48,199][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:49,069][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:49,984][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:50,526][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:50,632][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:51,056][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:51,093][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:51,636][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:51,828][onir_pt][DEBUG] [finished] train pairs: [3.81s] [1024it] [268.69it/s]

[2026-03-26 15:33:51,836][onir_pt][DEBUG] [finished] training [3.83s]
[2026-03-26 15:33:51,838][onir_pt][INFO] training   it=37 loss=0.2217
[2026-03-26 15:33:51,841][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:51,842][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:51,846][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:51,976][onir_pt][DEBUG] [finished] batches: [126ms] [63it] [500.45it/s]
[2026-03-26 15:33:52,092][onir_pt][DEBUG] [finished] validation [251ms]
[2026-03-26 15:33:52,094][onir_pt][INFO] validation it=37 map=0.0060 ndcg=0.0153 P_10=0.0720
[2026-03-26 15:33:52,096][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:52,099][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:52,101][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:53,517][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:53,592][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:53,905][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:54,505][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:55,301][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:55,899][onir_pt][DEBUG] [finished] train pairs: [3.79s] [1024it] [269.91it/s]

[2026-03-26 15:33:55,907][onir_pt][DEBUG] [finished] training [3.81s]
[2026-03-26 15:33:55,910][onir_pt][INFO] training   it=38 loss=0.2239
[2026-03-26 15:33:55,912][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:33:55,914][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:55,918][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:33:56,050][onir_pt][DEBUG] [finished] batches: [127ms] [63it] [494.80it/s]
[2026-03-26 15:33:56,168][onir_pt][DEBUG] [finished] validation [256ms]
[2026-03-26 15:33:56,170][onir_pt][INFO] validation it=38 map=0.0060 ndcg=0.0154 P_10=0.0720
[2026-03-26 15:33:56,172][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:33:56,176][onir_pt][DEBUG] [starting] training
[2026-03-26 15:33:56,178][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:33:56,320][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:57,011][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:57,372][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:57,541][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:58,269][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:58,669][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:58,803][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:58,946][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:59,374][onir_pt][DEBUG] not enough negs

[2026-03-26 15:33:59,509][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:00,040][onir_pt][DEBUG] [finished] train pairs: [3.86s] [1024it] [265.44it/s]

[2026-03-26 15:34:00,049][onir_pt][DEBUG] [finished] training [3.87s]
[2026-03-26 15:34:00,051][onir_pt][INFO] training   it=39 loss=0.2269
[2026-03-26 15:34:00,053][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:00,055][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:00,059][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:00,199][onir_pt][DEBUG] [finished] batches: [135ms] [63it] [466.14it/s]
[2026-03-26 15:34:00,314][onir_pt][DEBUG] [finished] validation [261ms]
[2026-03-26 15:34:00,316][onir_pt][INFO] validation it=39 map=0.0059 ndcg=0.0153 P_10=0.0700
[2026-03-26 15:34:00,319][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:00,323][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:00,326][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:03,078][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:03,181][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:03,486][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:03,832][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:04,035][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:04,133][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:04,250][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:04,284][onir_pt][DEBUG] [finished] train pairs: [3.95s] [1024it] [259.03it/s]

[2026-03-26 15:34:04,291][onir_pt][DEBUG] [finished] training [3.97s]
[2026-03-26 15:34:04,294][onir_pt][INFO] training   it=40 loss=0.2201
[2026-03-26 15:34:04,296][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:04,298][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:04,302][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:04,431][onir_pt][DEBUG] [finished] batches: [125ms] [63it] [504.09it/s]
[2026-03-26 15:34:04,546][onir_pt][DEBUG] [finished] validation [250ms]
[2026-03-26 15:34:04,548][onir_pt][INFO] validation it=40 map=0.0060 ndcg=0.0153 P_10=0.0720
[2026-03-26 15:34:04,550][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:04,555][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:04,557][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:04,986][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:06,304][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:06,607][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:06,964][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:07,045][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:08,427][onir_pt][DEBUG] [finished] train pairs: [3.87s] [1024it] [264.91it/s]

[2026-03-26 15:34:08,434][onir_pt][DEBUG] [finished] training [3.88s]
[2026-03-26 15:34:08,437][onir_pt][INFO] training   it=41 loss=0.2303
[2026-03-26 15:34:08,439][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:08,441][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:08,445][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:08,574][onir_pt][DEBUG] [finished] batches: [125ms] [63it] [504.24it/s]
[2026-03-26 15:34:08,688][onir_pt][DEBUG] [finished] validation [249ms]
[2026-03-26 15:34:08,690][onir_pt][INFO] validation it=41 map=0.0060 ndcg=0.0154 P_10=0.0720
[2026-03-26 15:34:08,694][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:08,696][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:08,698][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:09,503][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:10,672][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:11,551][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:12,498][onir_pt][DEBUG] [finished] train pairs: [3.80s] [1024it] [269.76it/s]

[2026-03-26 15:34:12,506][onir_pt][DEBUG] [finished] training [3.81s]
[2026-03-26 15:34:12,507][onir_pt][INFO] training   it=42 loss=0.2116
[2026-03-26 15:34:12,509][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:12,511][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:12,516][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:12,645][onir_pt][DEBUG] [finished] batches: [126ms] [63it] [501.37it/s]
[2026-03-26 15:34:12,758][onir_pt][DEBUG] [finished] validation [249ms]
[2026-03-26 15:34:12,760][onir_pt][INFO] validation it=42 map=0.0060 ndcg=0.0153 P_10=0.0700
[2026-03-26 15:34:12,762][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:12,766][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:12,769][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:13,282][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:13,704][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:14,878][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:14,912][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:15,270][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:15,638][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:15,717][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:15,787][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:16,086][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:16,105][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:16,305][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:16,559][onir_pt][DEBUG] [finished] train pairs: [3.79s] [1024it] [270.47it/s]

[2026-03-26 15:34:16,567][onir_pt][DEBUG] [finished] training [3.80s]
[2026-03-26 15:34:16,569][onir_pt][INFO] training   it=43 loss=0.2344
[2026-03-26 15:34:16,571][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:16,574][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:16,578][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:16,716][onir_pt][DEBUG] [finished] batches: [134ms] [63it] [468.43it/s]
[2026-03-26 15:34:16,831][onir_pt][DEBUG] [finished] validation [259ms]
[2026-03-26 15:34:16,833][onir_pt][INFO] validation it=43 map=0.0059 ndcg=0.0153 P_10=0.0700
[2026-03-26 15:34:16,836][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:16,839][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:16,841][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:17,436][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:17,583][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:18,107][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:19,695][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:20,045][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:20,630][onir_pt][DEBUG] [finished] train pairs: [3.78s] [1024it] [270.61it/s]

[2026-03-26 15:34:20,637][onir_pt][DEBUG] [finished] training [3.80s]
[2026-03-26 15:34:20,640][onir_pt][INFO] training   it=44 loss=0.2255
[2026-03-26 15:34:20,642][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:20,645][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:20,647][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:20,777][onir_pt][DEBUG] [finished] batches: [125ms] [63it] [502.68it/s]
[2026-03-26 15:34:20,889][onir_pt][DEBUG] [finished] validation [248ms]
[2026-03-26 15:34:20,891][onir_pt][INFO] validation it=44 map=0.0060 ndcg=0.0154 P_10=0.0740
[2026-03-26 15:34:20,893][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:20,897][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:20,898][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:21,030][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:21,156][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:21,593][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:22,192][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:22,510][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:22,952][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:24,040][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:24,610][onir_pt][DEBUG] [finished] train pairs: [3.71s] [1024it] [276.27it/s]

[2026-03-26 15:34:24,617][onir_pt][DEBUG] [finished] training [3.72s]
[2026-03-26 15:34:24,619][onir_pt][INFO] training   it=45 loss=0.2287
[2026-03-26 15:34:24,622][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:24,623][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:24,627][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:24,754][onir_pt][DEBUG] [finished] batches: [124ms] [63it] [507.98it/s]
[2026-03-26 15:34:24,875][onir_pt][DEBUG] [finished] validation [253ms]
[2026-03-26 15:34:24,876][onir_pt][INFO] validation it=45 map=0.0057 ndcg=0.0150 P_10=0.0600
[2026-03-26 15:34:24,878][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:24,882][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:24,884][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:25,267][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:25,655][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:27,263][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:27,512][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:27,875][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:27,994][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:28,335][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:28,432][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:28,542][onir_pt][DEBUG] [finished] train pairs: [3.65s] [1024it] [280.24it/s]

[2026-03-26 15:34:28,550][onir_pt][DEBUG] [finished] training [3.67s]
[2026-03-26 15:34:28,552][onir_pt][INFO] training   it=46 loss=0.2148
[2026-03-26 15:34:28,554][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:28,556][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:28,560][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:28,687][onir_pt][DEBUG] [finished] batches: [123ms] [63it] [511.81it/s]
[2026-03-26 15:34:28,800][onir_pt][DEBUG] [finished] validation [246ms]
[2026-03-26 15:34:28,802][onir_pt][INFO] validation it=46 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-26 15:34:28,804][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:28,808][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:28,810][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:28,981][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:29,128][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:29,282][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:30,057][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:30,605][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:30,912][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:31,402][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:32,609][onir_pt][DEBUG] [finished] train pairs: [3.79s] [1024it] [269.87it/s]

[2026-03-26 15:34:32,616][onir_pt][DEBUG] [finished] training [3.81s]
[2026-03-26 15:34:32,619][onir_pt][INFO] training   it=47 loss=0.2279
[2026-03-26 15:34:32,621][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:32,624][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:32,628][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:32,757][onir_pt][DEBUG] [finished] batches: [126ms] [63it] [500.97it/s]
[2026-03-26 15:34:32,873][onir_pt][DEBUG] [finished] validation [252ms]
[2026-03-26 15:34:32,875][onir_pt][INFO] validation it=47 map=0.0059 ndcg=0.0153 P_10=0.0720
[2026-03-26 15:34:32,877][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:32,882][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:32,884][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:32,966][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:33,878][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:34,042][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:34,436][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:34,768][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:35,029][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:35,944][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:36,187][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:36,589][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:36,663][onir_pt][DEBUG] [finished] train pairs: [3.77s] [1024it] [271.30it/s]

[2026-03-26 15:34:36,671][onir_pt][DEBUG] [finished] training [3.79s]
[2026-03-26 15:34:36,674][onir_pt][INFO] training   it=48 loss=0.2193
[2026-03-26 15:34:36,677][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:36,680][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:36,683][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:36,819][onir_pt][DEBUG] [finished] batches: [131ms] [63it] [479.42it/s]
[2026-03-26 15:34:36,934][onir_pt][DEBUG] [finished] validation [257ms]
[2026-03-26 15:34:36,936][onir_pt][INFO] validation it=48 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-26 15:34:36,939][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:36,941][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:36,943][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:38,113][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:38,215][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:38,592][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:39,001][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:39,390][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:39,530][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:40,099][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:40,392][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:40,704][onir_pt][DEBUG] [finished] train pairs: [3.76s] [1024it] [272.63it/s]

[2026-03-26 15:34:40,711][onir_pt][DEBUG] [finished] training [3.77s]
[2026-03-26 15:34:40,713][onir_pt][INFO] training   it=49 loss=0.2220
[2026-03-26 15:34:40,715][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:40,716][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:40,720][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:40,851][onir_pt][DEBUG] [finished] batches: [127ms] [63it] [497.27it/s]
[2026-03-26 15:34:40,972][onir_pt][DEBUG] [finished] validation [257ms]
[2026-03-26 15:34:40,974][onir_pt][INFO] validation it=49 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-26 15:34:40,976][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:40,980][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:40,981][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:41,122][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:41,449][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:41,720][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:41,908][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:41,930][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:42,728][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:42,910][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:43,188][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:43,269][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:44,385][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:44,639][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:44,768][onir_pt][DEBUG] [finished] train pairs: [3.78s] [1024it] [270.80it/s]

[2026-03-26 15:34:44,775][onir_pt][DEBUG] [finished] training [3.80s]
[2026-03-26 15:34:44,778][onir_pt][INFO] training   it=50 loss=0.2228
[2026-03-26 15:34:44,780][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:44,782][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:44,786][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:44,917][onir_pt][DEBUG] [finished] batches: [126ms] [63it] [498.12it/s]
[2026-03-26 15:34:45,033][onir_pt][DEBUG] [finished] validation [254ms]
[2026-03-26 15:34:45,035][onir_pt][INFO] validation it=50 map=0.0059 ndcg=0.0152 P_10=0.0700
[2026-03-26 15:34:45,038][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:45,041][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:45,043][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:45,338][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:46,593][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:47,460][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:48,002][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:48,403][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:48,735][onir_pt][DEBUG] [finished] train pairs: [3.69s] [1024it] [277.74it/s]

[2026-03-26 15:34:48,742][onir_pt][DEBUG] [finished] training [3.70s]
[2026-03-26 15:34:48,745][onir_pt][INFO] training   it=51 loss=0.2372
[2026-03-26 15:34:48,747][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:48,750][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:48,753][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:48,883][onir_pt][DEBUG] [finished] batches: [125ms] [63it] [502.21it/s]
[2026-03-26 15:34:48,996][onir_pt][DEBUG] [finished] validation [249ms]
[2026-03-26 15:34:48,999][onir_pt][INFO] validation it=51 map=0.0059 ndcg=0.0153 P_10=0.0700
[2026-03-26 15:34:49,001][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:49,004][onir_pt][DEBUG] [starting] training
[2026-03-26 15:34:49,007][onir_pt][DEBUG] [starting] train pairs

[2026-03-26 15:34:49,982][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:50,748][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:51,192][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:51,548][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:51,670][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:52,795][onir_pt][DEBUG] not enough negs

[2026-03-26 15:34:53,007][onir_pt][DEBUG] [finished] train pairs: [4.00s] [1024it] [256.21it/s]

[2026-03-26 15:34:53,015][onir_pt][DEBUG] [finished] training [4.01s]
[2026-03-26 15:34:53,018][onir_pt][INFO] training   it=52 loss=0.2202
[2026-03-26 15:34:53,020][onir_pt][DEBUG] [starting] validation
[2026-03-26 15:34:53,022][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:34:53,025][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:34:53,156][onir_pt][DEBUG] [finished] batches: [127ms] [63it] [497.28it/s]
[2026-03-26 15:34:53,272][onir_pt][DEBUG] [finished] validation [252ms]
[2026-03-26 15:34:53,274][onir_pt][INFO] validation it=52 map=0.0057 ndcg=0.0150 P_10=0.0680
[2026-03-26 15:34:53,277][onir_pt][INFO] early stopping; model reverting back to it=32

/usr/local/lib/python3.10/dist-packages/onir/rankers/base.py:68: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(path, map_location=torch.device('cpu')), strict=False)

In [18]:
pt.Experiment(
    [tfidf, pipeline],
    test_topics,
    qrels,
    names=['TFIDF', 'TFIDF >> KNRM (trained)'],
    eval_metrics=[AP(rel=2), nDCG, nDCG@10, P(rel=2)@10]
)

[2026-03-26 15:38:02,743][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:38:02,746][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:38:02,753][onir_pt][DEBUG] [finished] batches: [2ms] [0it] [?it/s]

/usr/local/lib/python3.10/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #1: TFIDF >> KNRM (trained) ((TerrierRetr(TF_IDF) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x78328bad38b0> >> onir(knrm,wordvec_hash)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-03-26 15:38:03,892][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:38:03,894][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:38:04,276][onir_pt][DEBUG] [finished] batches: [377ms] [188it] [498.74it/s]

                      name      nDCG   nDCG@10  AP(rel=2)  P(rel=2)@10
0                    TFIDF  0.123589  0.595818   0.054568     0.546667
1  TFIDF >> KNRM (trained)  0.122284  0.524899   0.051927     0.446667

#### Question ✍ OK
1. The result is higher, but still not as good as TFIDF. Propose a hypothesis on the problem.

**ANSWER :**

We can see an improvement in the KNRM method, it went from 0.4238 to 0.5214 in the nDCG@10 metric, this proves that the .fit method really worked and the model is learning. I think this can be explained by many reasons : 

- In the covid-19 dataset, if the user for example searches a very specific word, TF-IDF gives a huge weight to that match. Whereas KNRM weakens that signal by looking for synonyms or related concepts (semantic matches) which can introduce noise.
- With the code below, I also noticed that the number of queries is small (50 in total and then divided in training/test/validation) this can impact training of the KNRM model. Training a neural model like KNRM in a small batch of queries may be insufficient for it to catch up the TF-IDF method. With a much larger query dataset KNRM may improve and surpass TF-IDF.

In [19]:
print(f"Total Queries (Topics): {len(topics)}")
print(f"Training Queries: {len(train_topics)}")
# ==================================================== #
print(f"Validation Queries: {len(valid_topics)}")
print(f"Test Queries: {len(test_topics)}")

Total Queries (Topics): 50
Training Queries: 30
Validation Queries: 5
Test Queries: 15

In [20]:
print(index.getCollectionStatistics().toString())

Number of documents: 192509
Number of terms: 151235
Number of postings: 11554033
Number of fields: 0
Number of tokens: 17728468
Field names: []
Positions:   false

# III. Vanilla BERT

Contextualized language models, such as [BERT](https://arxiv.org/abs/1810.04805), are much more powerful neural models that have proven effective for classification.

We will try to use a “vanilla” (or “mono”) version of the BERT model. The BERT model is pre-trained for language modeling and next-sentence prediction.

In [21]:
del knrm # clear out memory from KNRM
vbert = onir_pt.reranker('vanilla_transformer', 'bert', text_field='abstract', vocab_config={'train': True})

100%|██████████| 231508/231508 [550ms<0ms, 421279.05B/s]
100%|██████████| 433/433 [0ms<0ms, 1336375.01B/s]
100%|██████████| 440473133/440473133 [52.53s<0ms, 8385423.34B/s]
/usr/local/lib/python3.10/dist-packages/pytorch_transformers/modeling_utils.py:477: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(resolved_archive_file, map_location='cpu')

Let's see how this model performs on the TREC CORD19 collection.

In [22]:
pipeline = tfidf % 50 >> get_text >> vbert
pt.Experiment(
    [tfidf, pipeline],
    test_topics,
    qrels,
    names=['TFIDF', 'TFIDF >> VBERT'],
    baseline=0,
    eval_metrics=[AP(rel=2), nDCG, nDCG@10, P(rel=2)@10]
)

[2026-03-26 15:39:25,705][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:39:25,855][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:39:25,861][onir_pt][DEBUG] [finished] batches: [2ms] [0it] [?it/s]

/usr/local/lib/python3.10/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #1: TFIDF >> VBERT ((TerrierRetr(TF_IDF) >> RankCutoff(50) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x78328bad38b0> >> onir(vanilla_transformer,bert)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-03-26 15:39:26,998][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:39:27,003][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:39:39,581][onir_pt][DEBUG] [finished] batches: [12.57s] [188it] [14.95it/s]

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,name,nDCG,nDCG@10,AP(rel=2),P(rel=2)@10,nDCG +,nDCG -,nDCG p-value,nDCG@10 +,nDCG@10 -,nDCG@10 p-value,AP(rel=2) +,AP(rel=2) -,AP(rel=2) p-value,P(rel=2)@10 +,P(rel=2)@10 -,P(rel=2)@10 p-value
0,TFIDF,0.123589,0.595818,0.054568,0.546667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TFIDF >> VBERT,0.121068,0.526283,0.051388,0.466667,4.0,11.0,0.537761,6.0,9.0,0.200217,4.0,11.0,0.249944,5.0,8.0,0.110861

As we can see, although the model is pre-trained, it doesn't perform very well. This is because it is not tuned for the relevance ranking task.

However, we can train the model for ranking (as described above for KNRM).

# IV. monoT5

The [monoT5 model](https://arxiv.org/abs/2003.06713) evaluates documents using a causal language model. Let's see how this approach works on TREC COVID.

The `MonoT5ReRanker` class in `pyterrier_t5` automatically loads a version of the monoT5 workbook, which is trained on the MS MARCO passage dataset.

In [23]:
from pyterrier_t5 import MonoT5ReRanker
monoT5 = MonoT5ReRanker(text_field='abstract')

spiece.model:   0%|          | 0.00/792k [7ms<?, ?B/s]

tokenizer.json: 0.00B [7ms, ?B/s]

config.json: 0.00B [7ms, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

config.json: 0.00B [6ms, ?B/s]

pytorch_model.bin:   0%|          | 0.00/892M [6ms<?, ?B/s]

In [24]:
pipeline = (tfidf >> get_text >> monoT5)
pt.Experiment(
    [tfidf, pipeline],
    test_topics,
    qrels,
    names=['TFIDF', 'TFIDF >> T5'],
    eval_metrics=[AP(rel=2), nDCG, nDCG@10, P(rel=2)@10, "mrt"]
)

monoT5:   0%|          | 0/188 [0ms<?, ?batches/s]Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.
monoT5: 100%|██████████| 188/188 [14.34s<0ms, 13.11batches/s]

          name      nDCG   nDCG@10  AP(rel=2)  P(rel=2)@10           mrt
0        TFIDF  0.123589  0.595818   0.054568     0.546667    636.853920
1  TFIDF >> T5  0.128997  0.700101   0.060670     0.606667  14902.100323

As expected, the results are much better in terms of NDCG@10 (0.5958 vs. 0.6855).

# Application

#### Question ✍

Simlar to the previous PW, use the models implemented for cord19 in a question-answer task.

In this context, queries are questions and documents are documents that might contain the answer.

Note that you'll need to redo the indexing as well as the other steps studied in this tutorial. You can download the dataset using the lines of code below.

In [25]:
fiqa = {}
fiqa['train'] = pt.datasets.get_dataset('irds:beir/fiqa/train')
fiqa['valid'] = pt.datasets.get_dataset('irds:beir/fiqa/dev')
fiqa['test'] = pt.datasets.get_dataset('irds:beir/fiqa/test')

test_topics = fiqa['test'].get_topics(variant='text')
test_qrels = fiqa['test'].get_qrels()

train_topics = fiqa['train'].get_topics(variant='text')
train_qrels = fiqa['train'].get_qrels()

valid_topics = fiqa['valid'].get_topics(variant='text')
valid_qrels = fiqa['valid'].get_qrels()

#Dataset pour créer l'index :
dataset_fiqa = pt.datasets.get_dataset('irds:beir/fiqa')

[INFO] [starting] opening zip file
[INFO] If you have a local copy of https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/17918ed23cd04fb15047f73e6c3bd9d9
[INFO] [starting] https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip
[INFO] [finished] https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip: [2.84s] [17.9MB] [6.33MB/s]
[INFO] [finished] opening zip file [4.19s]
[INFO] [starting] opening zip file
[INFO] [finished] opening zip file [2ms]
[INFO] [starting] opening zip file
[INFO] [finished] opening zip file [2ms]
[INFO] [starting] opening zip file
[INFO] [finished] opening zip file [2ms]

In [26]:
#### Your code here
import shutil

# Define where to store the index
fiqa_index_path = './terrier_fiqa'

# Clean up if an old index exists
if os.path.exists(fiqa_index_path):
    shutil.rmtree(fiqa_index_path)

# Create the indexer
# We specify 'text' as the metadata we want to retrieve later
indexer = pt.IterDictIndexer(fiqa_index_path, meta={'docno': 40, 'text': 10000}, fields=['text'])

# Run the indexing process on the FIQA corpus
indexref_fiqa = indexer.index(dataset_fiqa.get_corpus_iter())

# Load the index
index_fiqa = pt.IndexFactory.of(indexref_fiqa)

print("FIQA Indexing complete!")

[INFO] [starting] building docstore
[INFO] [starting] opening zip file
[INFO] [finished] opening zip file [5ms]
docs_iter: 100%|████████████████████████| 57638/57638 [1.50s<0ms, 38451.99doc/s]
[INFO] [finished] docs_iter: [1.50s] [57638doc] [38395.87doc/s]
[INFO] [finished] building docstore [1.51s]
beir/fiqa documents:   1%|          | 680/57638 [302ms<21.87s, 2604.09it/s]

15:41:31.742 [ForkJoinPool-2-worker-3] WARN org.terrier.structures.indexing.Indexer -- Adding an empty document to the index (7915) - further warnings are suppressed

beir/fiqa documents: 100%|██████████| 57638/57638 [12.72s<0ms, 4529.82it/s]

15:41:45.644 [ForkJoinPool-2-worker-3] WARN org.terrier.structures.indexing.Indexer -- Indexed 39 empty documents
FIQA Indexing complete!

In [36]:
# Standard Retriever (Fast)
tfidf_fiqa = pt.BatchRetrieve(index_fiqa, wmodel="TF_IDF")

# Neural Re-ranker (Smart)
# We use 'vanilla_transformer' which is the standard BERT model
import onir_pt
vbert_fiqa = onir_pt.reranker('vanilla_transformer', 'bert', batch_size = 2, max_iter = 10) #batchsize de 2 et maxiter de 10

# Text Fetcher
# This is the "bridge" that gets the text of the answers for BERT to read
get_text_fiqa = pt.text.get_text(dataset_fiqa, 'text')

print("Models and Text Fetcher initialized!")

<ipython-input-36-2e66f1270898>:2: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  tfidf_fiqa = pt.BatchRetrieve(index_fiqa, wmodel="TF_IDF")

TypeError: OpenNIRPyterrierReRanker.__init__() got an unexpected keyword argument 'batch_size'

In [28]:
# Pipeline logic: 
# 1. Get top 50 with TF-IDF 
# 2. Get the text for those 50
# 3. Let BERT re-rank them
pipeline_fiqa = (tfidf_fiqa % 50) >> get_text_fiqa >> vbert_fiqa

print("Pipeline is ready for evaluation.")

Pipeline is ready for evaluation.

Nettoyage des données (on enlève les carcatères spéciaux)

In [37]:
import re

def clean_query(text):
    # Supprime les caractères spéciaux : # : ? ! " ' ( )
    # On garde seulement les lettres, les chiffres et les espaces
    return re.sub(r'[^a-zA-Z0-9\s]', ' ', text)

for df in [train_topics, valid_topics, test_topics]:
    df["query"] = df["query"].apply(clean_query)
    # On enlève les espaces doubles créés par le nettoyage
    df["query"] = df["query"].str.replace(r'\s+', ' ', regex=True).str.strip()

print("Nettoyage terminé ! Le caractère '#1' est devenu ' 1', ce qui ne fera plus crasher Java.")

Nettoyage terminé ! Le caractère '#1' est devenu ' 1', ce qui ne fera plus crasher Java.

In [31]:
pt.Experiment(
    [tfidf_fiqa % 10, pipeline_fiqa], # Compare Baseline vs BERT
    test_topics,
    test_qrels,
    names=["TF-IDF", "TF-IDF >> BERT"],
    eval_metrics=["map", "ndcg", "ndcg_cut_10"]
)

[2026-03-26 15:57:29,172][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:57:29,179][onir_pt][DEBUG] [starting] batches

[2026-03-26 15:57:29,186][onir_pt][DEBUG] [finished] batches: [3ms] [0it] [?it/s]

/usr/local/lib/python3.10/dist-packages/pyterrier/_evaluation/_validation.py:76: UserWarning: Experiment Pipeline Validation Report

The following pipelines could not be validated (i.e., it is unclear what outputs they produce):
 - Pipeline #1: TF-IDF >> BERT ((TerrierRetr(TF_IDF) >> RankCutoff(50) >> <pyterrier.datasets._irds.IRDSTextLoader object at 0x7832c590b100> >> onir(vanilla_transformer,bert)))
If these pipelines work, set validate='ignore' to remove this warning, or make them inspectable to clarify how they work.

See https://pyterrier.readthedocs.io/en/latest/troubleshooting/inspection.html for more information.
  warn(message)

[2026-03-26 15:58:17,173][onir_pt][DEBUG] using GPU (deterministic)
[2026-03-26 15:58:17,180][onir_pt][DEBUG] [starting] batches

[2026-03-26 16:08:09,252][onir_pt][DEBUG] [finished] batches: [09:52] [8100it] [13.68it/s]

             name       map      ndcg  ndcg_cut_10
0          TF-IDF  0.193922  0.253339     0.253659
1  TF-IDF >> BERT  0.028437  0.131183     0.018809

In [39]:
pipeline_fiqa_fine = (tfidf_fiqa % 10) >> get_text_fiqa >> vbert_fiqa

print("Pipeline is ready for evaluation.")

Pipeline is ready for evaluation.

In [40]:
# On lance l'entraînement (Fine-tuning)
pipeline_fiqa_fine.fit(
    train_topics, 
    train_qrels, 
    valid_topics, 
    valid_qrels
)

KeyboardInterrupt:

fit que sur knrm

fit sur bert et monot5 est un plus

on fait la comparaison que ce avec qu'on a

#### Question ✍
Do you see any advantages compare to Learning to Rank?